name: project_environment
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=20.2
  - pip:
      - azure-ai-ml
      - azureml-defaults
      - azureml-dataprep>=1.6
      - protobuf <= 3.20.1
      - pyyaml
      - torch
      - torchmetrics>=0.7.0, <0.10.1
      - torchvision
      - numpy
      - onnx
      - scipy
      - onnxruntime
      - onnxconverter_common
      - git+https://github.com/microsoft/Olive.git
