trigger:
  batch: true
  branches:
    include:
    - main
pr: none

stages:
  - stage: Build_Docs
    jobs:
    - template: job_templates/olive-build-doc-template.yaml
      parameters:
        job_name: BuildDocs
        display_name: Build Docs
        pool: $(OLIVE_POOL_UBUNTU2004)

  - stage: Publish_Docs
    dependsOn: [Build_Docs]
    jobs:
    - job: PublishDocs
      displayName: Publish Docs
      pool: $(OLIVE_POOL_UBUNTU2004)

      steps:
      - checkout: self
        clean: true
        persistCredentials: true

      # checkout gh-pages branch and delete all files
      - script: |
          git config --global user.email "olivedevteam@microsoft.com"
          git config --global user.name "olivedevteam"
          git pull origin gh-pages
          git checkout gh-pages
          git rm -rf .
        displayName: Checkout gh-pages branch

      # copy the docs to the root of the repo
      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          artifact: olive_doc_src
          path: $(Build.SourcesDirectory)
        displayName: Download Docs from Pipeline Artifact

      # commit and push the docs
      - script: |
          git add -A
          git commit -m "Update docs from $(Build.SourceVersion)"
          git push origin gh-pages
        displayName: Commit and Push Docs
