parameters:
- name: doc_version
  displayName: "If it's doc build for released branch, please specify the version number."
  type: string
  default: 'latest'

trigger:
  batch: true
  branches:
    include:
    - main
pr:
  branches:
    include:
    - main

variables:
  runCodesignValidationInjection: false
  skipComponentGovernanceDetection: true

stages:
  - stage: Build_Docs
    jobs:
    - job: BuildDocs
      displayName: Build Docs
      pool: $(OLIVE_POOL_UBUNTU2004)
      variables:
        PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip

      steps:
      - template: job_templates/olive-setup-template.yaml
        parameters:
          python_version: '3.10'
          onnxruntime: 'onnxruntime'
          torch: 'torch'

      # checkout release branch if doc_version provided
      - script: |
          git config --global user.email "olivedevteam@microsoft.com"
          git config --global user.name "olivedevteam"
          git fetch origin rel-${{parameters.doc_version}}
          git checkout rel-${{parameters.doc_version}}
        displayName: Checkout release branch
        condition: ne('${{parameters.doc_version}}', 'latest')

      - script: |
          # set -e, otherwise make html fails but the build continues
          set -e
          cd docs
          python -m pip install -r requirements.txt
          make html
          make linkcheck
          make schema
        displayName: Make Docs

      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.SourcesDirectory)/docs/build/html
          artifactName: olive_doc_src
          artifactType: pipeline
        displayName: Publish Docs to Pipeline Artifact
        condition: ne(variables['Build.Reason'], 'PullRequest')

  - stage: Publish_Docs
    dependsOn: [Build_Docs]
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
    - job: PublishDocs
      displayName: Publish Docs
      pool: $(OLIVE_POOL_UBUNTU2004)

      steps:
      - checkout: self
        clean: true
        persistCredentials: true

      # checkout gh-pages branch and delete all files except released version folder in format x.x.x
      - script: |
          git config --global user.email "olivedevteam@microsoft.com"
          git config --global user.name "olivedevteam"
          git pull origin gh-pages
          git checkout gh-pages
          ls | grep -vE "[0-9]+\.[0-9]+\.[0-9]+" | xargs -d '\n' git rm -rf --
        displayName: Checkout gh-pages branch
        condition: eq('${{parameters.doc_version}}', 'latest')

      # copy the docs to the root of the repo
      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          artifact: olive_doc_src
          path: $(Build.SourcesDirectory)
        displayName: Download Docs from Pipeline Artifact
        condition: eq('${{parameters.doc_version}}', 'latest')

      # checkout gh-pages branch and delete files in version folder
      - script: |
          git config --global user.email "olivedevteam@microsoft.com"
          git config --global user.name "olivedevteam"
          git pull origin gh-pages
          git checkout gh-pages
          git rm -rf ${{parameters.doc_version}}
          mkdir ${{parameters.doc_version}}
        displayName: Checkout gh-pages branch
        condition: ne('${{parameters.doc_version}}', 'latest')

      # copy the docs to the version folder
      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          artifact: olive_doc_src
          path: $(Build.SourcesDirectory)/${{parameters.doc_version}}
        displayName: Download Docs from Pipeline Artifact
        condition: ne('${{parameters.doc_version}}', 'latest')

      # commit and push the docs
      - script: |
          ls -d */ | grep -E "[0-9]+\.[0-9]+\.[0-9]+" | xargs -I {} cp ./_static/js/custom_version.js {}_static/js/
          git add -A
          git commit -m "Update docs from $(Build.SourceVersion)"
          git push origin gh-pages
        displayName: Commit and Push Docs
