trigger:
  - main
pr:
  - main

pool:
  name: $(OLIVE_POOL_UBUNTU2004)

jobs:
  - job: Pylint
    strategy:
      matrix:
        Python37:
          python.version: "3.7"
        Python38:
          python.version: "3.8"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
        displayName: "Use Python $(python.version)"

      - script: |
          python -m pip install pre-commit
          pre-commit install
          pre-commit run --all-files
        displayName: "Formatting checks"
