trigger: none

pr: none

schedules:
- cron: '0 0 * * 1'
  displayName: Weekly build
  branches:
    include:
    - main

variables:
  runCodesignValidationInjection: false
  skipComponentGovernanceDetection: true

jobs:
# Linux examples test
- template: job_templates/olive-example-cpu-template.yaml
  parameters:
    name: Linux_Examples
    pool: $(OLIVE_POOL_UBUNTU2004)
    examples:
      mobilenet_onnx:
        exampleFolder: mobilenet/onnx
        exampleName: mobilenet

# Linux GPU examples testing.
- template: job_templates/olive-example-linux-gpu-template.yaml
  parameters:
    name: Linux_GPU_Examples
    pool: $(OLIVE_POOL_UBUNTU2004_GPU_V100)
    hf_token: true
    examples:
      mistral:
        exampleFolder: mistral
        exampleName: mistral_fp16
      phi2:
        exampleFolder: phi2
        exampleName: phi2
        exampleRequirements: requirements-pipeline.txt
