trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    - .github/*
    # commonly updated examples with no test
    - examples/deepseek/*
    - examples/directml/llm/*
    - examples/directml/stable_diffusion_xl/*
    - examples/llama2/*
    - examples/llama3/*
    - examples/mistral/*
    - examples/open_llama/*
    - examples/phi2/*
    - examples/phi3/*
    - examples/phi3_5/*
    - examples/qwen2_5/*
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    # unrelated pipelines
    - .github/*
    - .azure_pipelines/performance_check/*
    - .azure_pipelines/performance.yaml
    - .azure_pipelines/job_templates/olive-performance-template.yaml
    # commonly updated examples with no test
    - examples/deepseek/*
    - examples/directml/llm/*
    - examples/directml/stable_diffusion_xl/*
    - examples/llama2/*
    - examples/llama3/*
    - examples/mistral/*
    - examples/open_llama/*
    - examples/phi2/*
    - examples/phi3/*
    - examples/phi3_5/*
    - examples/qwen2_5/*

variables:
  runCodesignValidationInjection: false
  skipComponentGovernanceDetection: true

jobs:
# Linux unit tests
- template: job_templates/olive-test-cpu-template.yaml
  parameters:
    name: Linux_CPU_CI_Unit_Test
    pool: $(OLIVE_POOL_UBUNTU2004)

- template: job_templates/olive-test-linux-gpu-template.yaml
  parameters:
    name: Linux_GPU_CI_Unit_Test
    pool: $(OLIVE_POOL_UBUNTU2004_GPU_V100)

# Windows unit tests
- template: job_templates/olive-test-cpu-template.yaml
  parameters:
    name: Windows_CPU_CI_Unit_Test
    pool: $(OLIVE_POOL_WIN2019)
    windows: True

# Linux examples test
- template: job_templates/olive-example-cpu-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    examples:
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      mobilenet_qnn_ep:
        exampleFolder: mobilenet/qnn
        exampleName: mobilenet_qnn_ep

# Windows examples test
- template: job_templates/olive-example-cpu-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    examples:
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      mobilenet_qnn_ep:
        exampleFolder: mobilenet/qnn
        exampleName: mobilenet_qnn_ep
