trigger: none

pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily build
  branches:
    include:
    - main

variables:
  runCodesignValidationInjection: false
  skipComponentGovernanceDetection: true

jobs:
# Linux unit test
- template: job_templates/olive-test-cpu-template.yaml
  parameters:
    name: Linux_CI_Unit_Test_Olive
    pool: $(OLIVE_POOL_UBUNTU2004)
    windows: False
    onnxruntime_nightly: true

# Linux GPU unit test
- template: job_templates/olive-test-linux-gpu-template.yaml
  parameters:
    name: Linux_GPU_CI_Unit_Test_Olive
    pool: $(OLIVE_POOL_UBUNTU2004_GPU_V100)
    windows: False
    onnxruntime_nightly: true

# Windows unit test
- template: job_templates/olive-test-cpu-template.yaml
  parameters:
    name: Windows_CI_Unit_Test_Olive
    pool: $(OLIVE_POOL_WIN2019)
    windows: True
    onnxruntime_nightly: true
