trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
pr: none

jobs:
# Linux examples test
- template: job_templates/olive-example-linux-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    onnxruntime: onnxruntime
    subfolder: azureml
    examples:
      bert_ptq_cpu_aml:
        exampleFolder: bert
        exampleName: bert_ptq_cpu_aml
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu_aml
      resnet_vitis_ai_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_vitis_ai_ptq_cpu_aml
      llama2:
        exampleFolder: llama2
        exampleName: llama2
        exampleRequirements: requirements-pipeline.txt

# Windows examples test
- template: job_templates/olive-example-win-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    onnxruntime: onnxruntime
    subfolder: azureml
    examples:
      bert_ptq_cpu_aml:
        exampleFolder: bert
        exampleName: bert_ptq_cpu_aml
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu_aml
      resnet_vitis_ai_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_vitis_ai_ptq_cpu_aml
