trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    - .github/*
    # commonly updated examples with no test
    - examples/directml/llm/*
    - examples/directml/stable_diffusion_xl/*
    - examples/llama2/*
    - examples/mistral/*
    - examples/open_llama/*
    - examples/phi2/*
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    # unrelated pipelines
    - .github/*
    - .azure_pipelines/performance_check/*
    - .azure_pipelines/performance.yaml
    - .azure_pipelines/job_templates/olive-performance-template.yaml
    # commonly updated examples with no test
    - examples/directml/llm/*
    - examples/directml/stable_diffusion_xl/*
    - examples/llama2/*
    - examples/mistral/*
    - examples/open_llama/*
    - examples/phi2/*

variables:
  runCodesignValidationInjection: false
  skipComponentGovernanceDetection: true

jobs:
# Linux examples test
- template: job_templates/olive-example-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    onnxruntime: onnxruntime
    examples:
      mobilenet_qnn_toolkit:
        exampleFolder: mobilenet
        exampleName: qnn_tooklit


# Windows examples test
- template: job_templates/olive-example-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    onnxruntime: onnxruntime
    examples:
      mobilenet_qnn_toolkit:
        exampleFolder: mobilenet
        exampleName: qnn_tooklit
