trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    - .github/*
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    # unrelated pipelines
    - .github/*

variables:
  runCodesignValidationInjection: false
  skipComponentGovernanceDetection: true

jobs:
# Linux unit tests
- template: job_templates/olive-test-cpu-template.yaml
  parameters:
    name: Linux_CPU_CI_Unit_Test
    pool: $(OLIVE_POOL_UBUNTU2004)

- template: job_templates/olive-test-linux-gpu-template.yaml
  parameters:
    name: Linux_GPU_CI_Unit_Test
    pool: $(OLIVE_POOL_UBUNTU2004_GPU_V100)

# Windows unit tests
- template: job_templates/olive-test-cpu-template.yaml
  parameters:
    name: Windows_CPU_CI_Unit_Test
    pool: $(OLIVE_POOL_WIN2019)
    windows: True
