trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE

variables:
    ComponentDetection.Timeout: 2400

jobs:
- template: job_templates/olive-build-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    windows: False
    examples:
      cifar10_openvino_intel_hw:
        exampleFolder: cifar10_openvino_intel_hw
        exampleName: cifar10_openvino_intel_hw
      bert_ptq_cpu:
        exampleFolder: bert
        exampleName: bert_ptq_cpu
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      whisper:
        exampleFolder: whisper
        exampleName: whisper
      resnet_vitis_ai_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_vitis_ai_ptq_cpu
      bert_hf_cpu_aml:
        exampleFolder: bert
        exampleName: bert_hf_cpu_aml

- template: job_templates/olive-build-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    windows: True
    examples:
      cifar10_openvino_intel_hw:
        exampleFolder: cifar10_openvino_intel_hw
        exampleName: cifar10_openvino_intel_hw
      bert_ptq_cpu:
        exampleFolder: bert
        exampleName: bert_ptq_cpu
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      whisper:
        exampleFolder: whisper
        exampleName: whisper
      bert_hf_cpu_aml:
        exampleFolder: bert
        exampleName: bert_hf_cpu_aml

- template: job_templates/olive-build-doc-template.yaml
  parameters:
    job_name: Test_BuildDocs
    display_name: Test Build Docs
    pool: $(OLIVE_POOL_UBUNTU2004)
    publish_docs: false
