trigger: none

pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily build
  branches:
    include:
    - main

variables:
  runCodesignValidationInjection: false
  skipComponentGovernanceDetection: true

jobs:
# Linux unit test
- template: job_templates/olive-test-cpu-template.yaml
  parameters:
    name: Linux_CI_Unit_Test_Olive
    pool: $(OLIVE_POOL_UBUNTU2004)
    windows: False
    test_type: 'unit_test'
    onnxruntime_nightly: true

# Linux GPU unit test
- template: job_templates/olive-test-linux-gpu-template.yaml
  parameters:
    name: Linux_GPU_CI_Unit_Test_Olive
    pool: $(OLIVE_POOL_UBUNTU2004_GPU_V100)
    windows: False
    test_type: 'unit_test'
    onnxruntime_nightly: true

# Windows unit test
- template: job_templates/olive-test-cpu-template.yaml
  parameters:
    name: Windows_CI_Unit_Test_Olive
    pool: $(OLIVE_POOL_WIN2019)
    windows: True
    test_type: 'unit_test'
    onnxruntime_nightly: true

# Linux examples test
- template: job_templates/olive-example-linux-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    onnxruntime: onnxruntime
    onnxruntime_nightly: true
    examples:
      bert_ptq_cpu:
        exampleFolder: bert
        exampleName: bert_ptq_cpu
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      # resnet_vitis_ai_ptq_cpu:
      #   exampleFolder: resnet
      #   exampleName: resnet_vitis_ai_ptq_cpu
      resnet_qat:
        exampleFolder: resnet
        exampleName: resnet_qat
      whisper:
        exampleFolder: whisper
        exampleName: whisper
      mobilenet_qnn_ep:
        exampleFolder: mobilenet
        exampleName: mobilenet_qnn_ep

# # Windows examples test
- template: job_templates/olive-example-win-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    onnxruntime: onnxruntime
    onnxruntime_nightly: true
    examples:
      bert_ptq_cpu:
        exampleFolder: bert
        exampleName: bert_ptq_cpu
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      whisper:
        exampleFolder: whisper
        exampleName: whisper
      mobilenet_qnn_ep:
        exampleFolder: mobilenet
        exampleName: mobilenet_qnn_ep

# Linux GPU examples testing.
- template: job_templates/olive-example-linux-template.yaml
  parameters:
    name: Linux_GPU_CI
    pool: $(OLIVE_POOL_UBUNTU2004_GPU_V100)
    device: 'gpu'
    onnxruntime: onnxruntime-gpu
    onnxruntime_nightly: true
    dockerfile: '.azure_pipelines/dockerfiles/linux-gpu.dockerfile'
    base_image: 'mcr.microsoft.com/mirror/nvcr/nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04'
    trt_version: '10.5.0.18-1+cuda12.6'
    examples:
      bert_cuda_gpu:
        exampleFolder: bert
        exampleName: bert_cuda_gpu
      stable_diffusion_cuda_gpu:
        exampleFolder: stable_diffusion
        exampleName: stable_diffusion_cuda_gpu
        exampleRequirements: requirements-common.txt
