trigger: none

pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily build
  branches:
    include:
    - main

variables:
    ComponentDetection.Timeout: 2400

jobs:
- template: job_templates/olive-build-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    windows: False
    onnxruntime: ort-nightly
    enable_multiple_ep: False
    examples:
      bert_ptq_cpu:
        exampleFolder: bert
        exampleName: bert_ptq_cpu
      cifar10_openvino_intel_hw:
        exampleFolder: cifar10_openvino_intel_hw
        exampleName: cifar10_openvino_intel_hw
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      resnet_vitis_ai_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_vitis_ai_ptq_cpu
      resnet_qat:
        exampleFolder: resnet
        exampleName: resnet_qat
      whisper:
        exampleFolder: whisper
        exampleName: whisper

- template: job_templates/olive-build-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    windows: True
    onnxruntime: ort-nightly
    enable_multiple_ep: False
    examples:
      bert_ptq_cpu:
        exampleFolder: bert
        exampleName: bert_ptq_cpu
      cifar10_openvino_intel_hw:
        exampleFolder: cifar10_openvino_intel_hw
        exampleName: cifar10_openvino_intel_hw
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      resnet_qat:
        exampleFolder: resnet
        exampleName: resnet_qat
      whisper:
        exampleFolder: whisper
        exampleName: whisper

- template: job_templates/olive-build-template.yaml
  parameters:
    name: Linux_GPU_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    windows: False
    device: gpu
    onnxruntime: ort-nightly-gpu
    examples:
      bert_cuda_gpu:
        exampleFolder: bert
        exampleName: bert_cuda_gpu
