trigger: none

pr: none

schedules:
- cron: '0 0 * * 1'
  displayName: Weekly build
  branches:
    include:
    - main

variables:
  runCodesignValidationInjection: false
  skipComponentGovernanceDetection: true

jobs:
# Linux examples test
- template: job_templates/olive-example-cpu-template.yaml
  parameters:
    name: Linux_Examples
    pool: $(OLIVE_POOL_UBUNTU2004)
    examples:
      bert_inc:
        exampleFolder: bert
        exampleName: bert_inc
      resnet_vitis_ai_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_vitis_ai_ptq_cpu
      resnet_qat:
        exampleFolder: resnet
        exampleName: resnet_qat
      super_resolution:
        exampleFolder: super_resolution
        exampleName: super_resolution
      mobilenet_onnx:
        exampleFolder: mobilenet/onnx
        exampleName: mobilenet

# Windows examples test
- template: job_templates/olive-example-cpu-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    examples:
      bert_inc:
        exampleFolder: bert
        exampleName: bert_inc
      resnet_vitis_ai_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_vitis_ai_ptq_cpu
      resnet_qat:
        exampleFolder: resnet
        exampleName: resnet_qat
      super_resolution:
        exampleFolder: super_resolution
        exampleName: super_resolution

# Linux GPU examples testing.
- template: job_templates/olive-example-linux-gpu-template.yaml
  parameters:
    name: Linux_GPU_Examples
    pool: $(OLIVE_POOL_UBUNTU2004_GPU_V100)
    hf_token: true
    examples:
      mistral:
        exampleFolder: mistral
        exampleName: mistral_fp16
      phi2:
        exampleFolder: phi2
        exampleName: phi2
        exampleRequirements: requirements-pipeline.txt
