trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE

variables:
    ComponentDetection.Timeout: 2400

jobs:
# Linux unit test and integration test
- template: job_templates/olive-build-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    windows: False
    onnxruntime: onnxruntime

# Windows unit test and integration test
- template: job_templates/olive-build-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    windows: True
    onnxruntime: onnxruntime

# Linux examples test
- template: job_templates/olive-example-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    onnxruntime: onnxruntime
    examples:
      bert_ptq_cpu:
        exampleFolder: bert
        exampleName: bert_ptq_cpu
      bert_ptq_cpu_aml:
        exampleFolder: bert
        exampleName: bert_ptq_cpu_aml
      bert_ptq_cpu_docker:
        exampleFolder: bert
        exampleName: bert_ptq_cpu_docker
      cifar10_openvino_intel_hw:
        exampleFolder: cifar10_openvino_intel_hw
        exampleName: cifar10_openvino_intel_hw
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      resnet_vitis_ai_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_vitis_ai_ptq_cpu
      resnet_qat:
        exampleFolder: resnet
        exampleName: resnet_qat
      whisper:
        exampleFolder: whisper
        exampleName: whisper

# # Windows examples test
- template: job_templates/olive-example-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    onnxruntime: onnxruntime
    examples:
      bert_ptq_cpu:
        exampleFolder: bert
        exampleName: bert_ptq_cpu
      bert_ptq_cpu_aml:
        exampleFolder: bert
        exampleName: bert_ptq_cpu_aml
      cifar10_openvino_intel_hw:
        exampleFolder: cifar10_openvino_intel_hw
        exampleName: cifar10_openvino_intel_hw
      resnet_ptq_cpu:
        exampleFolder: resnet
        exampleName: resnet_ptq_cpu
      resnet_qat:
        exampleFolder: resnet
        exampleName: resnet_qat
      whisper:
        exampleFolder: whisper
        exampleName: whisper

# Linux GPU examples testing.
- template: job_templates/olive-example-template.yaml
  parameters:
    name: Linux_GPU_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    onnxruntime: onnxruntime-gpu
    examples:
      bert_cuda_gpu:
        exampleFolder: bert
        exampleName: bert_cuda_gpu

# Multiple EP Linux testing
- template: job_templates/olive-test-template.yaml
  parameters:
    name: Linux_CI_Multiple_EP_Test_Olive
    pool: $(OLIVE_POOL_UBUNTU2004)
    device: 'cpu'
    windows: 'False'
    test_type: 'multiple_ep'
    onnxruntime: onnxruntime
    python_version: '3.8'

# Multiple EP Windows testing
- template: job_templates/olive-test-template.yaml
  parameters:
    name: Windows_CI_Multiple_EP_Test_Olive
    pool: $(OLIVE_POOL_WIN2019)
    device: 'cpu'
    windows: 'True'
    test_type: 'multiple_ep'
    onnxruntime: onnxruntime
    python_version: '3.10'

# build documents
- template: job_templates/olive-build-doc-template.yaml
  parameters:
    job_name: Test_BuildDocs
    display_name: Test Build Docs
    pool: $(OLIVE_POOL_UBUNTU2004)
    publish_docs: false
