parameters:
- name: is_publish_build
  displayName: 'Whether publish package to pypi.'
  type: boolean
  default: false

trigger: none

pool:
  name: $(OLIVE_POOL_UBUNTU2004)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: python -m pip install --upgrade pip setuptools wheel twine
  displayName: 'Install tools'

- script: |
    python setup.py bdist_wheel
  displayName: 'Build package'

- task: CredScan@3
  displayName: 'Run CredScan'
  inputs:
    debugMode: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '*.whl'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    ArtifactName: olive

- script: |
    python -m twine upload --repository-url https://upload.pypi.org/legacy/ -u $(PYPI_USERNAME) -p $(PYPI_PASSWORD) dist/*.whl
  displayName: 'Upload to PyPI'
  condition: eq('${{ parameters.is_publish_build }}', true)
