trigger: none
pr: none

schedules:
- cron: 0 6 * * 5
  displayName: Scheduled Build
  branches:
    include:
    - main
  always: true


jobs:
- template: job_templates/olive-performance-template.yaml
  parameters:
    name: Linux_CPU_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    windows: False
    device: cpu
    examples:
      bert:
        model_name: bert
      distilbert:
        model_name: distilbert
      deberta:
        model_name: deberta
      roberta_large:
        model_name: roberta_large

- template: job_templates/olive-performance-template.yaml
  parameters:
    name: Linux_GPU_CI
    pool: $(OLIVE_GPU_POOL_UBUNTU2004)
    windows: False
    device: gpu
    examples:
      bert:
        model_name: bert
      distilbert:
        model_name: distilbert
      deberta:
        model_name: deberta
      roberta_large:
        model_name: roberta_large
