name: project_environment
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.2
  - pip:
      - datasets
      - optimum
      - sentencepiece
      - transformers
      - git+https://github.com/microsoft/Olive#egg=olive-ai[gpu]
