name: project_environment
channels:
  - defaults
dependencies:
  - python=3.9.21
  - pip=22.3.1
  - pip:
      - datasets
      - optimum
      - sentencepiece
      - transformers
      - git+https://github.com/microsoft/Olive#egg=olive-ai[gpu]
