name: project_environment
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=22.3.1
  - pip:
      - accelerate
      - bitsandbytes
      - peft
      - scikit-learn
      - sentencepiece
      - datasets
      - evaluate
      - psutil
      - optimum
      - scipy
      - scikit-learn
      - torch
      - onnxruntime-genai
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - transformers>=4.41.1
      - git+https://github.com/microsoft/Olive#egg=olive-ai[gpu,azureml]
