name: project_environment
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip=22.4
  - pip:
      - datasets
      - evaluate
      - optimum
      - psutil
      - scipy
      - scikit-learn
      - torch
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - transformers>=4.41.1
      - git+https://github.com/microsoft/Olive#egg=olive-ai[gpu]
