name: project_environment
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=22.3.1
  - pip:
      - datasets
      - evaluate
      - optimum
      - psutil
      - scipy
      - scikit-learn
      - torch
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - transformers>=4.41.1
      - git+https://github.com/microsoft/Olive#egg=olive-ai[cpu]
