name: project_environment
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=22.3.1
  - pip:
      - datasets
      - evaluate
      - scipy
      - scikit-learn
      - transformers
      - git+https://github.com/microsoft/Olive.git@myguo/pydantic_2#egg=olive-ai[cpu]
      - pydantic==2.*
