name: project_environment
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=22.3.1
  - pip:
      - onnxruntime
      - datasets
      - scipy
      - transformers
      - onnxconverter_common
      - git+https://github.com/microsoft/Olive.git
