name: project_environment
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip=22.4
  - pip:
      - accelerate
      - azure-keyvault-secrets
      - azure-identity
      - bitsandbytes
      - datasets
      - huggingface_hub
      - optimum
      - peft
      - scipy
      - sentencepiece
      - torch==2.0.1
      - transformers>=4.33.2,<= 4.37.2
      - git+https://github.com/microsoft/Olive#egg=olive-ai[gpu]
