name: project_environment
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=22.3.1
  - pip:
      - accelerate
      - azure-keyvault-secrets
      - azure-identity
      - bitsandbytes
      - datasets
      - huggingface_hub
      - peft
      - scipy
      - sentencepiece
      - torch==2.0.1
      - transformers>=4.33.2,<= 4.37.2
      - git+https://github.com/microsoft/Olive#egg=olive-ai[gpu]
