# FROM ubuntu:18.04
FROM nvidia/cuda:10.0-base

RUN apt-get update && apt-get install -y python3.7 libgomp1 cuda-cublas-10-0

RUN mkdir /testmodel
COPY resnet50 /testmodel/resnet50

RUN mkdir /perf_test
COPY bin /perf_test/bin
COPY perf_test.py /perf_test

WORKDIR /

ENTRYPOINT [ "python3.7", "/perf_test/perf_test.py"]