site_name: OLIVE Documentation
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: images/OLive_logo.png #https://artwork.lfaidata.foundation/projects/onnx/icon/white/onnx-icon-white.png
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    #- navigation.expand
    - navigation.indexes
    - navigation.path
    #- navigation.footer
    #- toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
  icon:
    annotation: material/chevron-right-circle
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: blue grey
      accent: blue

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: blue
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          #paths: [..]
          load_external_modules: false
          options:
            show_source: true
            docstring_style: google
            annotations_path: source
            allow_inspection: true
            show_bases: true
            find_stubs_package: false
            inherited_members: false
            show_inheritance_diagram: false
            merge_init_into_class: false
            show_if_no_docstring: false
            show_signature_annotations: false

nav:
  - Home: index.md
  - Overview: why-olive.md
  - Getting started: getting-started/getting-started.md
  # - Tutorials:
  #   - tutorials/index.md
  #   - Optimize for Windows: tutorials/optimize-for-windows.md
  #   - Optimize for Android: tutorials/optimize-for-android.md
  #   - Optimize for Apple: tutorials/optimize-for-apple.md
  - How-to:
    - how-to/index.md
    - Set-up:
      - Install Olive: how-to/installation.md
    - Use the CLI:
      - Auto Optimization: how-to/cli/cli-auto-opt.md
      - Finetune: how-to/cli/cli-finetune.md
      - Quantize: how-to/cli/cli-quantize.md
    - Configure Workflows:
      - Data: how-to/configure-workflows/how-to-configure-data.md
      - Systems: how-to/configure-workflows/systems.md
      - Metrics: how-to/configure-workflows/metrics-configuration.md
      - Passes:
        - Overview: how-to/configure-workflows/pass-configuration.md
        - Quantizations:
          - PyTorch: how-to/configure-workflows/quantization-pytorch.md
          - ONNX: how-to/configure-workflows/quantization-onnx.md
        - Optimizations & Transformations:
          - PyTorch: how-to/configure-workflows/model-opt-and-transform/pytorch.md
          - ONNX: how-to/configure-workflows/model-opt-and-transform/onnx.md
          - OpenVino: how-to/configure-workflows/model-opt-and-transform/openvino.md
          - SNPE: how-to/configure-workflows/model-opt-and-transform/snpe.md
          - QNN: how-to/configure-workflows/model-opt-and-transform/qnn.md
        - Model conversions:
          - Pytorch: how-to/configure-workflows/convert_pytorch.md
          - ONNX: how-to/configure-workflows/convert_onnx.md
      - Cloud Model Cache: how-to/configure-workflows/cloud-model-cache.md
      - Model Packaging: how-to/configure-workflows/model-packaging.md
      - Automatic Optimizer: how-to/configure-workflows/auto-opt.md
      - Integrations:
        - Azure AI: how-to/configure-workflows/azure-ai.md
        - Hugging Face: how-to/configure-workflows/hugging-face-integration.md
  - Reference:
    - api/index.md
    - CLI: api/cli-reference.md
    - Configurations: api/config-reference.md
  - Extending Olive:
    - extending/index.md
    - Design: extending/design.md
    - Adding a new optimization pass: extending/how_to_add_optimization_pass.md
    - Custom scripts: extending/custom_scripts.md
