name: project_environment
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip=20.2
  - pip:
      - onnxruntime
      - pytorch-lightning
      - psutil
      - scipy
      - tabulate
      - torchvision
      - git+https://github.com/microsoft/Olive#egg=olive-ai[cpu]
