name: project_environment
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=20.2
  - pip:
      - onnxruntime
      - pytorch-lightning
      - scipy
      - tabulate
      - torchvision
      - git+https://github.com/microsoft/Olive.git
