# Example Linux test template for Olive pipeline

parameters:
  name: ''
  pool: ''
  dockerfile: '.azure_pipelines/dockerfiles/linux-gpu.dockerfile'
  docker_image: 'olive-pipeline:latest'
  base_image: 'mcr.microsoft.com/mirror/nvcr/nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04'
  trt_version: '10.5.0.18-1+cuda12.6'
  python_version: '3.10'
  onnxruntime: 'onnxruntime-gpu'
  torch: 'torch'
  requirements_file: 'requirements-test-gpu.txt'
  test_script: 'run_test.sh'
  onnxruntime_nightly: false

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 300
  pool:
    name: ${{ parameters.pool}}
  variables:
    PIP_CACHE_DIR: /mnt/storage/.cache/pip
    HF_HOME: /mnt/storage/.cache/huggingface

  steps:
  - script: |
      set -euxo pipefail

      # Move agent work directory to /mnt/storage via symlink
      AGENT_ROOT=$(dirname "$(Agent.BuildDirectory)")
      sudo mkdir -p /mnt/storage/vss_work
      sudo chown -R $USER:$USER /mnt/storage/vss_work
      sudo cp -a "$AGENT_ROOT"/* /mnt/storage/vss_work/ 2>/dev/null || true
      sudo rm -rf "$AGENT_ROOT"
      sudo ln -sf /mnt/storage/vss_work "$AGENT_ROOT"

      # Move Docker and containerd to /mnt/storage
      sudo systemctl stop docker containerd
      sudo mkdir -p /mnt/storage/docker /mnt/storage/containerd /etc/containerd
      echo '{"data-root": "/mnt/storage/docker"}' | sudo tee /etc/docker/daemon.json
      containerd config default | sed 's|/var/lib/containerd|/mnt/storage/containerd|g' | sudo tee /etc/containerd/config.toml > /dev/null
      sudo systemctl start containerd docker

      # Move /tmp to /mnt/storage
      sudo mkdir -p /mnt/storage/tmp
      sudo chmod 1777 /mnt/storage/tmp
      sudo mount --bind /mnt/storage/tmp /tmp
    displayName: Move pipeline to /mnt/storage

  - template: build-docker-image-template.yaml
    parameters:
      python_version: ${{ parameters.python_version }}
      dockerfile: ${{ parameters.dockerfile }}
      docker_image: ${{ parameters.docker_image }}
      base_image: ${{ parameters.base_image }}
      trt_version: ${{ parameters.trt_version }}

  - script: |
      docker run \
      --shm-size=4g \
      --gpus=all \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v $(Build.SourcesDirectory)/logs:/logs \
      ${{ parameters.docker_image }} \
      bash .azure_pipelines/scripts/${{ parameters.test_script }} \
      ${{ parameters.torch }} \
      ${{ parameters.onnxruntime }} \
      ${{ parameters.onnxruntime_nightly }} \
      test/${{ parameters.requirements_file }} \
      test \
      false \
      $(hf_token)
    displayName: Run Tests in Docker

  - task: CredScan@3
    displayName: 'Run CredScan'
    inputs:
      debugMode: false
    continueOnError: true

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/*TestOlive*.xml'
      testRunTitle: '$(Build.BuildNumber)[$(Agent.JobName)]'
      failTaskOnFailedTests: true
      failTaskOnMissingResultsFile: true
    displayName: Upload pipeline run test results

  - script: sudo git clean -dfX
    condition: always()
    displayName: Clean remaining artifacts
