# Olive Build Doc Template

parameters:
  job_name: ''
  display_name: ''
  pool: ''
  publish_docs: false
  doc_version: 'latest'

jobs:
  - job: ${{parameters.job_name}}
    displayName: ${{parameters.display_name}}
    pool: ${{ parameters.pool}}

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.8
      displayName: Use Python 3.8

    # checkout release branch if doc_version provided
    - script: |
        git config --global user.email "olivedevteam@microsoft.com"
        git config --global user.name "olivedevteam"
        git fetch origin rel-${{parameters.doc_version}}
        git checkout rel-${{parameters.doc_version}}
      displayName: Checkout release branch
      condition: ne('${{parameters.doc_version}}', 'latest')

    - script: make install-olive INSTALL_EXTRAS=[cpu]
      displayName: Install Olive

    - script: |
        cd docs
        python -m pip install -r requirements.txt
        make html
        make linkcheck
      displayName: Make Docs

    - task:  PublishPipelineArtifact@1
      inputs:
        path: $(Build.SourcesDirectory)/docs/build/html
        artifactName: olive_doc_src
        artifactType: pipeline
      displayName: Publish Docs to Pipeline Artifact
      condition: and(succeeded(), eq('${{ parameters.publish_docs }}', 'true'))
