parameters:
  model_name: ''
  pool: ''
  device: 'cpu'

jobs:
- job: ${{ parameters.device }}_Model_Performance
  timeoutInMinutes: 300
  pool:
    name: ${{ parameters.pool }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.examples }}
  variables:
    WINDOWS: ${{ parameters.windows }}
    runCodesignValidationInjection: false
    device: ${{ parameters.device }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
    displayName: Use Python 3.8

  - script: python -m pip install .[$(device)]
    displayName: Install Olive

  - script: |
      python -m pip install -r $(Build.SourcesDirectory)/.azure_pipelines/performance_check/requirements-${{ parameters.device }}.txt
      python $(Build.SourcesDirectory)/.azure_pipelines/performance_check/run_performance_check.py --model_name $model_name --device ${{ parameters.device }}

      # clean up
      rm -rf $(Build.SourcesDirectory)/.azure_pipelines/performance_check/run_cache
    displayName: Run performance comparison

  - task: CredScan@3
    displayName: 'Run CredScan'
    inputs:
      debugMode: false
    continueOnError: true

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
    displayName: Component Detection

  - script: git clean -dfX
    condition: always()
    displayName: Clean remaining artifacts
