# Olive Build and Test Pipeline template on Azure DevOps

parameters:
  name: ''
  pool: ''
  device: 'cpu'
  onnxruntime: 'onnxruntime'

jobs:
- template: olive-test-template.yaml
  parameters:
    name: ${{parameters.name}}_Unit_Test_Olive
    pool: ${{parameters.pool}}
    device: ${{parameters.device}}
    WINDOWS: ${{parameters.windows}}
    test_type: 'unit_test'
    onnxruntime: ${{parameters.onnxruntime}}

- template: olive-test-template.yaml
  parameters:
    name: ${{parameters.name}}_Integration_Test_Olive
    pool: ${{parameters.pool}}
    device: ${{parameters.device}}
    WINDOWS: ${{parameters.windows}}
    test_type: 'integ_test'
    onnxruntime: ${{parameters.onnxruntime}}

- job: ${{parameters.name}}_Test_Examples
  timeoutInMinutes: 300
  pool:
    name: ${{ parameters.pool}}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.examples }}
  variables:
    WINDOWS: ${{ parameters.windows }}
    runCodesignValidationInjection: false
    device: ${{ parameters.device }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
    displayName: Use Python 3.8

  - script: pip install .
    displayName: Install Olive

  - ${{ if startsWith(parameters.onnxruntime, 'ort-nightly') }}:
    - script: |
        pip install onnxruntime
        pip uninstall -y onnxruntime
        pip install ${{ parameters.onnxruntime }} --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
      displayName: Install ${{ parameters.onnxruntime }}
  - ${{ else }}:
    - script: |
        pip install ${{ parameters.onnxruntime }}
      displayName: Install ${{ parameters.onnxruntime }}

  - task: AzureCLI@1
    inputs:
      azureSubscription: $(OLIVE_RG_SERVICE_CONNECTION)
      scriptLocation: 'inlineScript'
      inlineScript: |
        python -m pip install pytest
        python -m pip install -r $(Build.SourcesDirectory)/examples/$(exampleFolder)/requirements.txt
        python -m pytest -v -s --log-cli-level=WARNING --junitxml=$(Build.SourcesDirectory)/logs/test_examples-TestOlive.xml $(Build.SourcesDirectory)/examples/test/test_$(exampleName).py
    displayName: Test Examples
    env:
      OLIVEWHEELS_STORAGE_CONNECTION_STRING: $(olive-wheels-storage-connection-string)
      WORKSPACE_SUBSCRIPTION_ID: $(workspace-subscription-id)
      WORKSPACE_RESOURCE_GROUP: $(workspace-resource-group)
      WORKSPACE_NAME: $(workspace-name)
      AZURE_TENANT_ID: $(azure-tenant-id)
      AZURE_CLIENT_ID: $(olive-rg-sp-id)
      AZURE_CLIENT_SECRET: $(olive-rg-sp-secret)

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
    displayName: Component Detection

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/*TestOlive*.xml'
      testRunTitle: '$(Build.BuildNumber)[$(Agent.JobName)]'
    displayName: Upload pipeline run test results

  - script: git clean -dfX
    condition: always()
    displayName: Clean remaining artifacts

- template: olive-test-template.yaml
  parameters:
    name: ${{parameters.name}}_Multiple_EP_Test_Olive
    pool: ${{parameters.pool}}
    device: ${{parameters.device}}
    WINDOWS: ${{parameters.windows}}
    test_type: 'multiple_ep'
    onnxruntime: ${{parameters.onnxruntime}}
    ${{ if eq(parameters.windows, 'True') }}:
      python_version: '3.10'
    ${{ else }}:
      python_version: '3.8'
