name: project_environment
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=22.3.1
  - pip:
      - azure-ai-ml
      - azure-identity
      - azureml-defaults
      - azureml-dataprep==4.8.4
      - onnxruntime==1.13.1
      - datasets
      - scipy
      - transformers
      - onnxconverter_common
      - azureml-evaluate-mlflow
      - mlflow
      - git+https://github.com/microsoft/Olive.git
